### ISSUE TITLE
Explore OpenAPI SDK Generetors

### ISSUE THREAD

**Issue by Schavras** [indera-solutions/nima#14]
Based on the latest decision about the shape of responses and backend objects, we want to try to explore the idea of generating sdk (for starters ts/axios), but hopefully for other languages too, by using the existing swagger / openapi tags we have on the api routes and DTOs

Helpfull links

[openapi-generator-cli](https://github.com/OpenAPITools/openapi-generator-cli)

**Comment by JohnBelly95** [comment]
I think a command that saved the openapi spec in the repository would also be appreciated. It would allow for easy porting to applications like Postman for testing.
