### ISSUE TITLE
Add Environmental Variables

### ISSUE THREAD

**Issue by Schavras** [indera-solutions/nima#16]
We have some env we want to load in the api and the dashboard like:

### API
- DB_HOST
- DB_NAME
- DB_USERNAME
- DB_PASSWORD
- S3_BUCKET
- PORT

### DASHBOARD
- BASE_URL

@JohnBelly95 Missing anything?

**Comment by JohnBelly95** [comment]
None that I can think of off the top of my head. 

I also did some research on those environment.ts and environment.prod.ts files that were generated with the application. Seems like they are leftovers from the baseline node.js app generator and meant to be used with custom config loaders [as can be seen in the nest documentation](https://docs.nestjs.com/techniques/configuration#custom-configuration-files).

It seems like a viable solution for handling env variables and general configuration, though I'm not sure where further configuration would be needed this early in the projects lifetime.
